;kernel's Userland variables and constants
%define SYSTEMPATH          'SYSTEM/'
%define SYSTEMBINARIESPATH  'SYSTEM/BINARIES/'
%define SYSTEMLIBRARYPATH   'SYSTEM/LIBRARY/'
%define SYSTEMICONSPATH     'SYSTEM/ICONS/'
%define SYSTEMFONTSPATH     'SYSTEM/FONTS/'
%define SYSTEMUSERSPATH     'SYSTEM/USERS/'      ;this is path to symbolic links to mounted drives for users, their files and programs
%define SYSTEMROOTPATH      'SYSTEM/USERS/ROOT/' ;this is also path to symbolic link